apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: demo-domain
  namespace: tap-workload
  description: Demo Domain for Tanzu Application Platform
  annotations:
    "backstage.io/techdocs-ref": dir:.
spec:
  owner: tap-poc-team

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-web-app
  namespace: tap-workload
  description: Python Flask Web App
  tags:
    - app-accelerator
    - python
    - flask
    - gunicorn
    - web
    - tanzu
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=python-web-app"
    "backstage.io/techdocs-ref": dir:.
spec:
  type: service
  lifecycle: experimental
  owner: default-team
  providesApis:
    - demo-api
  system: demo-app

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo-app
  namespace: tap-workload
  description: Demo Application for Tanzu Application Platform
  annotations:
    "backstage.io/techdocs-ref": dir:.
spec:
  owner: demo-team
  domain: demo-domain

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  namespace: tap-workload
  description: The demo API for Tanzu Application Platform GUI
  links:
    - url: https://api.agify.io
      title: API Definition
      icon: docs
spec:
  type: openapi
  lifecycle: experimental
  owner: demo-team
  system: demo-app # Or specify system name of your choice
  definition: |
    openapi: 3.0.1
    info:
      title: Demo API
      description: defaultDescription
      version: '0.1'
    servers:
      - url: https://api.agify.io
    paths:
      /:
        get:
          description: Auto generated using Swagger Inspector
          parameters:
            - name: name
              in: query
              schema:
                type: string
              example: type_any_name
          responses:
            '200':
              description: Auto generated using Swagger Inspector
              content:
                application/json; charset=utf-8:
                  schema:
                    type: string
                  examples: {}
